export const SET_STORY = "ROUTER/SET_STORY"
export const SET_PAGE = "ROTER/SET_PAGE"
export const GO_BACK = "ROUTER/GO_BACK"

export const OPEN_SNACKBAR = "ROUTER/OPEN_SNACKBAR"
export const CLOSE_SNACKBAR = "ROUTER/CLOSE_SNACKBAR"
